In [1]:
import pandas as pd

In [2]:
DIABETIC_DATA_PATH = '../data/diabetic_data.csv'

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
df = pd.read_csv(DIABETIC_DATA_PATH,na_values=['?'])

/tmp/ipykernel_698347/3985722151.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DIABETIC_DATA_PATH,na_values=['?'])

In [5]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
df.shape

(101766, 50)

In [7]:
df.isna().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [8]:
df.drop(["max_glu_serum","A1Cresult"],axis=1,inplace=True)

In [9]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'metformin', 'repaglinide',
       'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide',
       'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone',
       'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide',
       'examide', 'citoglipton', 'insulin', 'glyburide-metformin',
       'glipizide-metformin', 'glimepiride-pioglitazone',
       'metformin-rosiglitazone', 'metformin-pioglitazone', 'change',
       'diabetesMed', 'readmitted'],
      dtype='object')

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
cols = df.columns

In [12]:
df[cols[18:]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   diag_1                    101745 non-null  object
 1   diag_2                    101408 non-null  object
 2   diag_3                    100343 non-null  object
 3   number_diagnoses          101766 non-null  int64
 4   metformin                 101766 non-null  object
 5   repaglinide               101766 non-null  object
 6   nateglinide               101766 non-null  object
 7   chlorpropamide            101766 non-null  object
 8   glimepiride               101766 non-null  object
 9   acetohexamide             101766 non-null  object
 10  glipizide                 101766 non-null  object
 11  glyburide                 101766 non-null  object
 12  tolbutamide               101766 non-null  object
 13  pioglitazone              101766 non-null  object
 14  rosiglitazone             101766 non-null  object
 15  acarbose                  101766 non-null  object
 16  miglitol                  101766 non-null  object
 17  troglitazone              101766 non-null  object
 18  tolazamide                101766 non-null  object
 19  examide                   101766 non-null  object
 20  citoglipton               101766 non-null  object
 21  insulin                   101766 non-null  object
 22  glyburide-metformin       101766 non-null  object
 23  glipizide-metformin       101766 non-null  object
 24  glimepiride-pioglitazone  101766 non-null  object
 25  metformin-rosiglitazone   101766 non-null  object
 26  metformin-pioglitazone    101766 non-null  object
 27  change                    101766 non-null  object
 28  diabetesMed               101766 non-null  object
 29  readmitted                101766 non-null  object
dtypes: int64(1), object(29)
memory usage: 23.3+ MB

In [13]:
print(df.isnull().sum().sort_values(ascending=False))

weight                      98569
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
gender                          0
discharge_disposition_id        0
admission_type_id               0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
age                             0
patient_nbr                     0
encounter_id                    0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_inpatient                0
number_emergency                0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [14]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [15]:
df['diag_3'].value_counts()

diag_3
250       11555
401        8289
276        5175
428        4577
427        3955
414        3664
496        2605
403        2357
585        1992
272        1969
599        1941
V45        1389
250.02     1369
707        1360
780        1334
285        1200
425        1136
250.6      1080
424        1063
584         963
305         924
250.01      915
682         887
518         854
41          727
493         694
278         680
530         625
786         584
491         574
486         568
244         540
V58         501
250.4       429
411         399
280         398
357         394
287         388
785         388
197         385
511         380
402         375
787         358
788         353
412         346
593         339
V15         334
413         329
438         318
250.8       316
998         316
294         315
799         312
571         310
560         306
295         305
995         299
997         298
789         290
458         285
535         285
996         281
70          281
426         272
536         267
263         252
578         250
V42         243
300         241
V10         239
198         238
784         236
396         229
440         221
E849        219
311         217
715         214
296         214
453         211
V43         211
410         209
303         207
112         206
443         205
V12         204
733         201
250.41      199
790         194
8           190
562         189
730         186
331         185
162         181
416         170
492         169
E878        164
342         164
38          162
304         159
515         155
397         150
577         149
250.92      149
724         148
729         147
433         143
553         141
250.7       141
591         140
284         138
574         136
250.03      134
781         133
466         132
E888        131
250.42      130
250.51      128
564         127
731         126
286         125
404         124
202         122
722         121
782         119
E885        117
250.82      113
288         113
250.5       111
794         110
710         109
558         108
648         107
728         107
569         107
196         105
459         104
211         100
581          97
337          97
719          96
V85          96
583          92
301          89
596          88
332          88
348          87
437          87
V09          86
507          84
275          84
714          83
455          81
290          81
293          81
327          80
600          79
242          77
716          77
681          75
250.52       74
E932         71
465          71
255          69
274          68
203          67
204          66
362          66
429          66
592          65
292          64
135          64
568          62
V46          60
340          60
344          59
E879         59
250.43       59
435          58
V54          58
783          57
473          57
490          56
482          56
434          56
153          55
441          54
V49          54
721          53
218          53
E942         52
573          52
572          51
595          51
185          51
531          50
250.81       50
625          49
590          47
253          47
79           46
V64          45
199          45
576          45
309          45
444          44
291          43
575          43
174          43
517          42
282          41
924          40
447          39
250.12       39
345          39
289          39
157          38
E947         38
298          38
277          38
873          38
456          38
V27          37
512          37
238          36
281          36
807          36
250.53       35
726          34
346          34
642          33
415          33
519          33
368          33
338          33
478          32
812          32
727          31
723          31
333          31
537          31
614          31
618          30
626          30
E935         30
620          29
V62          29
555          29
532          28
398          28
446          28
616          28
659          27
319          27
189          27
805          27
V44          27
999          26
588          26
E880         26
356          26
423          25
369          25
53           25
617          25
711          25
E884         24
442          24
V65          24
920          24
252          24
42           23
696          23
567          23
738          23
533          23
959          22
457          22
736          22
V17          22
E934         22
94           21
461          21
824          21
E812         21
138          21
E939         20
110          20
601          20
250.83       20
386          20
E944         20
250.1        20
802          20
737          20
813          19
365          19
808          19
205          19
V08          19
343          19
745          19
250.11       18
820          18
V66          18
646          18
355          18
627          17
266          17
611          17
358          17
923          17
E950         17
487          17
394          17
462          17
307          16
905          16
E933         16
556          16
477          16
792          16
349          16
725          16
709          16
922          16
693          16
692          15
753          15
261          15
V18          15
586          15
552          15
250.22       15
188          15
E930         15
494          14
54           14
598          14
663          14
664          14
382          14
312          14
713          14
250.93       14
791          14
183          14
570          13
454          13
389          13
654          13
150          13
796          13
501          13
516          13
557          13
840          13
514          13
V63          13
521          13
608          13
154          13
621          13
155          12
273          12
201          12
310          12
680          12
V14          12
378          12
647          12
E931         12
582          12
283          12
250.13       12
522          12
916          11
351          11
694          11
656          11
686          11
317          11
208          10
420          10
E928         10
823          10
151          10
607          10
698          10
969          10
241          10
380          10
883          10
432          10
867          10
958          10
279          10
405           9
580           9
741           9
260           9
E881          9
845           9
318           9
594           9
907           9
892           9
746           9
747           9
718           9
695           9
451           9
354           9
836           9
E816          9
250.9         9
579           9
200           9
262           8
962           8
704           8
793           8
945           8
V72           8
E819          8
372           8
649           8
610           8
705           8
861           8
V55           8
436           8
250.2         8
383           7
179           7
708           7
825           7
E927          7
117           7
658           7
225           7
E870          7
251           7
712           7
V53           7
270           7
991           7
E929          7
E936          7
V16           7
431           7
V57           7
359           7
652           7
717           7
965           7
228           7
917           6
821           6
E938          6
934           6
644           6
379           6
E937          6
E887          6
605           6
619           6
297           6
246           6
701           6
758           6
810           6
227           6
366           6
239           6
131           6
421           6
909           6
756           6
34            6
882           6
660           6
881           6
250.91        6
860           6
527           6
9             5
233           5
V13           5
E941          5
240           5
V61           5
336           5
913           5
464           5
891           5
388           5
V03           5
172           5
510           5
752           5
908           5
182           5
751           5
623           5
472           5
742           5
508           5
E850          5
306           5
815           5
E906          5
566           5
191           5
506           5
163           5
220           5
256           5
847           5
334           5
481           5
665           5
313           4
180           4
299           4
915           4
E858          4
543           4
831           4
335           4
906           4
V02           4
235           4
347           4
910           4
V60           4
259           4
921           4
801           4
661           4
E917          4
500           4
604           4
523           4
141           4
E818          4
826           4
865           4
495           4
452           4
653           4
323           4
V23           4
528           4
550           4
171           4
156           4
850           4
250.21        4
35            4
565           4
170           4
373           3
214           3
445           3
842           3
851           3
5             3
866           3
E943          3
844           3
933           3
703           3
525           3
314           3
816           3
655           3
685           3
534           3
919           3
912           3
78            3
152           3
417           3
470           3
161           3
862           3
E980          3
E905          3
529           3
759           3
245           3
E956          3
258           3
E920          3
E916          3
966           3
852           3
V86           3
353           3
132           3
720           3
268           3
223           2
702           2
E901          2
948           2
V06           2
624           2
928           2
360           2
430           2
800           2
795           2
E946          2
822           2
848           2
989           2
690           2
374           2
483           2
480           2
V25           2
706           2
192           2
136           2
734           2
139           2
911           2
376           2
3             2
173           2
E855          2
250.3         2
870           2
641           2
460           2
V11           2
670           2
953           2
216           2
E817          2
250.23        2
11            2
341           2
956           2
943           2
967           2
854           2
350           2
918           2
643           2
735           2
7             2
E924          2
88            2
797           2
377           2
864           2
384           2
E852          2
271           2
814           2
597           2
E919          2
V70           2
868           2
E813          2
215           1
V22           1
E966          1
879           1
E853          1
538           1
E900          1
875           1
952           1
669           1
811           1
930           1
381           1
E915          1
391           1
V01           1
893           1
236           1
841           1
622           1
E955          1
E912          1
463           1
E864          1
217           1
877           1
E922          1
111           1
123           1
E892          1
838           1
757           1
484           1
E886          1
E987          1
V07           1
837           1
863           1
E828          1
540           1
E865          1
148           1
880           1
308           1
732           1
697           1
524           1
E883          1
744           1
951           1
E876          1
243           1
970           1
395           1
158           1
871           1
115           1
972           1
385           1
387           1
75            1
602           1
E861          1
27            1
315           1
E945          1
47            1
987           1
E965          1
17            1
66            1
265           1
944           1
E904          1
193           1
853           1
884           1
E815          1
485           1
542           1
872           1
E825          1
122           1
890           1
E949          1
E882          1
E822          1
935           1
195           1
164           1
657           1
992           1
754           1
684           1
755           1
361           1
603           1
E826          1
250.31        1
186           1
674           1
226           1
365.44        1
146           1
955           1
E894          1
475           1
980           1
834           1
448           1
175           1
49            1
876           1
230           1
57            1
E854          1
942           1
14            1
750           1
370           1
671           1
971           1
Name: count, dtype: int64

#### Stuff to drop

In [16]:
df.drop(["weight","medical_specialty","payer_code"],axis=1,inplace=True)

##### Stuff to impute

In [17]:
df.fillna(df.mode().iloc[0], inplace=True)

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="most_frequent")
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [19]:
df_imputed.isna().sum().sort_values(ascending=False)

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [20]:
df.shape

(101766, 45)

In [21]:
df.to_csv('../data/diabetic_data_cleaned.csv',index=False)

##### Merge Part

In [22]:
MAPPING_CLEANED_DATA_PATH = '../data/IDS_mapping_cleaned.csv'

In [23]:
df_mapping = pd.read_csv(MAPPING_CLEANED_DATA_PATH)

In [24]:
new_one = df.merge(df_mapping, how='inner', left_on='admission_type_id', right_on='admission_type_id')
new_one.head(n=5)
new_one.shape

(305298, 46)

In [25]:
new_one.head(n=5)

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,description
0,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,0,1,0,0,0,250.83,276,250,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN
1,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,0,1,0,0,0,250.83,276,250,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Discharged/transferred to home with home healt...
2,2278392,8222157,Caucasian,Female,[0-10),6,25,1,1,41,0,1,0,0,0,250.83,276,250,1,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,Transfer from another health care facility
3,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Emergency
4,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,Discharged to home

In [26]:
new_one.to_csv('../data/full_data_cleaned.csv', index=False)